apiVersion: v1
kind: Service
metadata:
  name: cd
spec:
  selector:
    app: cd
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd-deployment
  labels:
    app: cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cd
  template:
    metadata:
      labels:
        app: cd
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: helix-cd
        image: devexcontainers.azurecr.io/helix-cd
        ports:
        - containerPort: 80
        env:
        - name: Database_Username
          valueFrom:
            secretKeyRef:
              name: sitecore-database
              key: username
        - name: Database_Password
          valueFrom:
            secretKeyRef:
              name: sitecore-database
              key: password
        - name: Sitecore_License
          valueFrom:
            secretKeyRef:
              name: sitecore-license
              key: license
        - name: Sitecore_ConnectionStrings_Security
          value: Data Source=mssql;Initial Catalog=Sitecore.Core;User ID=$(Database_Username);Password=$(Database_Password)
        - name: Sitecore_ConnectionStrings_Web
          value: Data Source=mssql;Initial Catalog=Sitecore.Web;User ID=$(Database_Username);Password=$(Database_Password)
        - name: Sitecore_ConnectionStrings_ExperienceForms
          value: Data Source=mssql;Initial Catalog=Sitecore.ExperienceForms;User ID=$(Database_Username);Password=$(Database_Password)
        - name: Sitecore_ConnectionStrings_Solr.Search
          value: http://solr:8983/solr
        - name: Sitecore_ConnectionStrings_Redis.Sessions
          value: redis:6379,ssl=False,abortConnect=False
        - name: Sitecore_Identity_Server_Authority
          value: http://id.helix.aks
        - name: Sitecore_Identity_Server_InternalAuthority
          value: http://id
        - name: Sitecore_Identity_Server_Require_Https
          value: "false"
        livenessProbe:
          httpGet:
            path: /healthz/ready
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Liveness
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /healthz/ready
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Startup
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 10
      imagePullSecrets:
      - name: devexregistry