apiVersion: v1
kind: Service
metadata:
  name: cm
spec:
  selector:
    app: cm
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-deployment
  labels:
    app: cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm
  template:
    metadata:
      labels:
        app: cm
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: helix-cm
        image: devexcontainers.azurecr.io/helix-cm
        ports:
        - containerPort: 80
        env:
        - name: Database_Username
          valueFrom:
            secretKeyRef:
              name: sitecore-database
              key: username
        - name: Database_Password
          valueFrom:
            secretKeyRef:
              name: sitecore-database
              key: password
        - name: Sitecore_ConnectionStrings_Sitecoreidentity.secret
          valueFrom:
            secretKeyRef:
              name: sitecore-identity
              key: secret
        - name: Sitecore_AppSettings_Telerik.AsyncUpload.ConfigurationEncryptionKey
          valueFrom:
            secretKeyRef:
              name: sitecore-telerik
              key: encryptionkey
        - name: Sitecore_AppSettings_Telerik.Upload.ConfigurationHashKey
          valueFrom:
            secretKeyRef:
              name: sitecore-telerik
              key: encryptionkey
        - name: Sitecore_AppSettings_Telerik.Web.UI.DialogParametersEncryptionKey
          valueFrom:
            secretKeyRef:
              name: sitecore-telerik
              key: encryptionkey
        - name: Sitecore_License
          valueFrom:
            secretKeyRef:
              name: sitecore-license
              key: license
        - name: Sitecore_ConnectionStrings_Core
          value: Data Source=mssql;Initial Catalog=Sitecore.Core;User ID=$(Database_Username);Password=$(Database_Password)
        - name: Sitecore_ConnectionStrings_Security
          value: Data Source=mssql;Initial Catalog=Sitecore.Core;User ID=$(Database_Username);Password=$(Database_Password)
        - name: Sitecore_ConnectionStrings_Master
          value: Data Source=mssql;Initial Catalog=Sitecore.Master;User ID=$(Database_Username);Password=$(Database_Password)
        - name: Sitecore_ConnectionStrings_Web
          value: Data Source=mssql;Initial Catalog=Sitecore.Web;User ID=$(Database_Username);Password=$(Database_Password)
        - name: Sitecore_ConnectionStrings_ExperienceForms
          value: Data Source=mssql;Initial Catalog=Sitecore.ExperienceForms;User ID=$(Database_Username);Password=$(Database_Password)
        - name: Sitecore_ConnectionStrings_Solr.Search
          value: http://solr:8983/solr
        - name: Sitecore_Identity_Server_Authority
          value: http://id.helix.aks
        - name: Sitecore_Identity_Server_InternalAuthority
          value: http://id
        - name: Sitecore_Identity_Server_Require_Https
          value: "false"
        livenessProbe:
          httpGet:
            path: /healthz/ready
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Liveness
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /healthz/ready
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Startup
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 10
      imagePullSecrets:
      - name: devexregistry