apiVersion: v1
kind: Service
metadata:
  name: id
spec:
  selector:
    app: id
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-deployment
  labels:
    app: id
spec:
  replicas: 1
  selector:
    matchLabels:
      app: id
  template:
    metadata:
      labels:
        app: id
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: helix-id
        image: devexcontainers.azurecr.io/helix-id
        ports:
        - containerPort: 80
        env:
        - name: Database_Username
          valueFrom:
            secretKeyRef:
              name: sitecore-database
              key: username
        - name: Database_Password
          valueFrom:
            secretKeyRef:
              name: sitecore-database
              key: password
        - name: Sitecore_Sitecore__IdentityServer__Clients__PasswordClient__ClientSecrets__ClientSecret1
          valueFrom:
            secretKeyRef:
              name: sitecore-identity
              key: secret
        - name: Sitecore_Sitecore__IdentityServer__CertificateRawData
          valueFrom:
            secretKeyRef:
              name: sitecore-identity
              key: certificate
        - name: Sitecore_Sitecore__IdentityServer__CertificateRawDataPassword
          valueFrom:
            secretKeyRef:
              name: sitecore-identity
              key: certificate-password
        - name: Sitecore_License
          valueFrom:
            secretKeyRef:
              name: sitecore-license
              key: license
        - name: Sitecore_Sitecore__IdentityServer__SitecoreMemberShipOptions__ConnectionString
          value: Data Source=mssql;Initial Catalog=Sitecore.Core;User ID=$(Database_Username);Password=$(Database_Password)
        - name: Sitecore_Sitecore__IdentityServer__AccountOptions__PasswordRecoveryUrl
          value: http://cm.helix.aks/sitecore/login?rc=1
        - name: Sitecore_Sitecore__IdentityServer__Clients__DefaultClient__AllowedCorsOrigins__AllowedCorsOriginsGroup1
          value: http://cm.helix.aks
        - name: Sitecore_Sitecore__IdentityServer__PublicOrigin
          value: http://id.helix.aks
        livenessProbe:
          httpGet:
            path: /healthz/ready
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Liveness
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /healthz/ready
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Startup
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 10
      imagePullSecrets:
      - name: devexregistry
