trigger: none

resources:
- repo: self

variables:
  azureSubscriptionEndpoint: 'devexcontainers-rm'
  registry: 'devexcontainers.azurecr.io'
  kubernetesServiceConnection: 'DevExCluster-default'
  registryServiceConnection: 'DevExContainers'
  sitecoreRegistryServiceConnection: 'sitecore-docker-registry'
  imagePullSecret: 'devexregistry'

stages:
- stage: Build
  displayName: Build stage

  jobs:  
  - job: Build
    displayName: Build and push images
    pool: Default
    steps:
    
    - task: Docker@2
      displayName: Login to DevExContainers registry
      inputs:
        containerRegistry: '$(registryServiceConnection)'
        command: login
        
    - task: Docker@2
      displayName: Login to Sitecore registry
      inputs:
        containerRegistry: '$(sitecoreRegistryServiceConnection)'
        command: login 

    - task: DockerCompose@0
      displayName: Build images
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: '$(azureSubscriptionEndpoint)'
        azureContainerRegistry: '$(registry)'
        dockerComposeFile: 'examples/helix-basic-tds-consolidated/docker-compose.yml'
        additionalDockerComposeFiles: ./docker-compose.override.yml
        dockerComposeFileArgs: |
          REGISTRY=$(registry)/
          VERSION=$(VERSION)
          SOLUTION_BUILD_IMAGE=mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019
          Nuget_SitecorePreview_Username=$(Nuget_SitecorePreview_Username)
          Nuget_SitecorePreview_Password=$(Nuget_SitecorePreview_Password)
          TDS_Owner=$(TDS_Owner)
          TDS_Key=$(TDS_Key)
        action: 'Build services'
        includeLatestTag: true
        arguments: '--force-rm'
        currentWorkingDirectory: 'examples/helix-basic-tds-consolidated'

    - task: DockerCompose@0
      displayName: Push images
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: '$(azureSubscriptionEndpoint)'
        azureContainerRegistry: '$(registry)'
        dockerComposeFile: 'examples/helix-basic-tds-consolidated/docker-compose.yml'
        additionalDockerComposeFiles: ./docker-compose.override.yml
        dockerComposeFileArgs: |
          REGISTRY=$(registry)/
          VERSION=$(VERSION)
          Nuget_SitecorePreview_Username=$(Nuget_SitecorePreview_Username)
          Nuget_SitecorePreview_Password=$(Nuget_SitecorePreview_Password)
          TDS_Owner=$(TDS_Owner)
          TDS_Key=$(TDS_Key)
        action: 'Push services'
        includeLatestTag: true
        currentWorkingDirectory: 'examples/helix-basic-tds-consolidated'

    - task: KubernetesManifest@0
      name: bake
      displayName: Bake K8s manifests
      inputs:
        action: 'bake'
        namespace: 'default'
        renderType: 'kustomize'
        kustomizationPath: 'examples/helix-basic-tds-consolidated/k8s/'

    - publish: $(bake.manifestsBundle)
      artifact: manifests
      
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:  
  - deployment: Deploy
    displayName: Deploy to AKS
    pool: Default
    environment: 'HelixExamplesInternal.default'
    strategy:
      runOnce:
        deploy:
          steps:
          
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: 'default'
              secretType: 'dockerRegistry'
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(registryServiceConnection)
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: 'default'
              manifests: $(Pipeline.Workspace)/manifests/*
              containers: |
                $(registry)/helix-redis:$(VERSION)
                $(registry)/helix-mssql:$(VERSION)
                $(registry)/helix-solr:$(VERSION)
                $(registry)/helix-id:$(VERSION)
                $(registry)/helix-cm:$(VERSION)
                $(registry)/helix-cd:$(VERSION)
              imagePullSecrets: |
                $(imagePullSecret)