trigger: none

resources:
- repo: self

variables:
  azureSubscriptionEndpoint: devexcontainers-rm
  azureContainerRegistry: devexcontainers.azurecr.io

stages:
- stage: Build
  displayName: Build and push services
  jobs:  
  - job: Build
    displayName: Build
    pool: Default
    steps:
    
    - task: Docker@2
      displayName: Login to DevExContainers registry
      inputs:
        containerRegistry: DevExContainers
        command: login
        
    - task: Docker@2
      displayName: Login to Sitecore registry
      inputs:
        containerRegistry: sitecore-docker-registry
        command: login 

    - task: DockerCompose@0
      displayName: Build services
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: '$(azureSubscriptionEndpoint)'
        azureContainerRegistry: '$(azureContainerRegistry)'
        dockerComposeFile: 'examples/helix-basic-tds-consolidated/docker-compose.build.yml'
        dockerComposeFileArgs: |
          REGISTRY=$(azureContainerRegistry)/
          VERSION=$(VERSION)
          BUILD_BUILD_IMAGE=mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019
          Nuget_SitecorePreview_Username=$(Nuget_SitecorePreview_Username)
          Nuget_SitecorePreview_Password=$(Nuget_SitecorePreview_Password)
          TDS_Owner=$(TDS_Owner)
          TDS_Key=$(TDS_Key)
        action: 'Build services'
        includeLatestTag: true
        arguments: '--force-rm'
        currentWorkingDirectory: 'examples/helix-basic-tds-consolidated'

    - task: DockerCompose@0
      displayName: Push services
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: '$(azureSubscriptionEndpoint)'
        azureContainerRegistry: '$(azureContainerRegistry)'
        dockerComposeFile: 'examples/helix-basic-tds-consolidated/docker-compose.build.yml'
        dockerComposeFileArgs: |
          REGISTRY=$(azureContainerRegistry)/
          VERSION=$(VERSION)
          Nuget_SitecorePreview_Username=$(Nuget_SitecorePreview_Username)
          Nuget_SitecorePreview_Password=$(Nuget_SitecorePreview_Password)
          TDS_Owner=$(TDS_Owner)
          TDS_Key=$(TDS_Key)
        action: 'Push services'
        includeLatestTag: true
        currentWorkingDirectory: 'examples/helix-basic-tds-consolidated'