trigger: none

resources:
- repo: self

variables:
  azureSubscriptionEndpoint: devexcontainers-rm
  azureContainerRegistry: devexcontainers.azurecr.io
  projectName: 'helix'
  tag: '$(Build.BuildId)'
  vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: Build and push services
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    
    - task: Docker@1
      displayName: Login to Sitecore registry
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: sitecore-docker-registry
        command: login 

    - task: DockerCompose@0
      displayName: Build services
      inputs:
        action: Build services
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureContainerRegistry: $(azureContainerRegistry)
        currentWorkingDirectory: '$(System.DefaultWorkingDirectory)/examples/helix-basic-tds-consolidated'
        dockerComposeFile: 'docker-compose.build.yml'
        dockerComposeFileArgs: |
          REGISTRY=devexcontainers.azurecr.io/
          BUILD_BUILD_IMAGE=mcr.microsoft.com/dotnet/framework/sdk:4.8
          BUILD_BASE_IMAGE=mcr.microsoft.com/windows/nanoserver:1809
          TOOLING_BUILD_IMAGE=mcr.microsoft.com/windows/servercore:ltsc2019
          TOOLING_BASE_IMAGE=mcr.microsoft.com/windows/nanoserver:1809
          SITECORE_DOCKER_REGISTRY=do-hrbr-01-dk1.dk.sitecore.net/platform/
          SITECORE_VERSION=9.4.0.003727.51-10.0.17763.973-ltsc2019
          Nuget_SitecorePreview_Username=$(Nuget_SitecorePreview_Username)
          Nuget_SitecorePreview_Password=$(Nuget_SitecorePreview_Password)
          TDS_Owner=$(TDS_Owner)
          TDS_Key=$(TDS_Key)
        projectName: $(projectName)
        qualifyImageNames: true
        additionalImageTags: $(tag)
        includeLatestTag: true

    - task: DockerCompose@0
      displayName: Push services
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: '$(azureSubscriptionEndpoint)'
        azureContainerRegistry: '$(azureContainerRegistry)'
        currentWorkingDirectory: '$(System.DefaultWorkingDirectory)/examples/helix-basic-tds-consolidated'
        dockerComposeFile: 'examples/helix-basic-tds-consolidated/docker-compose.build.yml'
        dockerComposeFileArgs: 'REGISTRY=devexcontainers.azurecr.io/'
        projectName: '$(projectName)'
        action: 'Push services'
        additionalImageTags: '$(tag)'
        includeLatestTag: true