version: "2.4"

services:

  build:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-build:${VERSION:-latest}
    build:
      context: .
      dockerfile: build.Dockerfile
      args:
        BASE_IMAGE: ${BUILD_BASE_IMAGE}
        BUILD_IMAGE: ${BUILD_BUILD_IMAGE}
        Nuget_SitecorePreview_Username: ${Nuget_SitecorePreview_Username}
        Nuget_SitecorePreview_Password: ${Nuget_SitecorePreview_Password}
        TDS_Owner: ${TDS_Owner}
        TDS_Key: ${TDS_Key}

  tooling:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-tooling:${VERSION:-latest}
    build:
      context: ./docker/build/tooling
      args:
        TOOLING_BASE_IMAGE: ${TOOLING_BASE_IMAGE}
        TOOLING_BUILD_IMAGE: ${TOOLING_BUILD_IMAGE}

  cm:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-cm:${VERSION:-latest}
    build:
      context: ./docker/build/cm
      target: ${BUILD_TARGET:-debug}
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-cm:${SITECORE_VERSION}
        BUILD_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-build:${VERSION:-latest}
        TOOLING_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-tooling:${VERSION:-latest}
    depends_on:
      - build
      - tooling

  cd:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-cd:${VERSION:-latest}
    build:
      context: ./docker/build/cd
      target: ${BUILD_TARGET:-debug}
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-cd:${SITECORE_VERSION}
        BUILD_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-build:${VERSION:-latest}
        TOOLING_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-tooling:${VERSION:-latest}
    depends_on:
      - build
      - tooling