---
ID: "f0607916-6fe7-5fab-8638-8f01c981dd80"
Parent: "d391cfa8-aa29-5201-86d7-8aaa98af11e8"
Template: "d391cfa8-aa29-5201-86d7-8aaa98af11e8"
Path: "/sitecore/templates/Project/basiccompany/Styleguide-FieldUsage-Checkbox/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210203T190051Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3a188cd4-a51e-4352-b483-3fabf69344df"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210203T190051Z
