---
ID: "02d5fe3b-f523-5190-b3a0-a556467199f2"
Parent: "8280e9d0-442e-5d33-8e1a-5da0f4d35d5b"
Template: "8280e9d0-442e-5d33-8e1a-5da0f4d35d5b"
Path: "/sitecore/templates/Project/basiccompany/Styleguide-FieldUsage-ItemLink/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210203T190054Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d6438a40-a7a6-4989-aad2-89da0b5cfdd0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210203T190054Z
